import Link from "next/link";
import {
  Roboto
} from "next/font/google"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  style: ["italic", "normal"],
  subsets: ["latin"]
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <nav>
          <Link href='/'>Home</Link> <br />
          <Link href='/about'>About</Link> <br />
          <Link href='/posts'>Posts</Link> <br />
          <br />
          <Link href='/tienda'>Tienda</Link> <br />
        </nav>
        {children}
        </body>
    </html>
  );
}
