import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav>
          <Link href='/'>Home</Link> <br />
          <Link href='/about'>About</Link> <br />
          <Link href='/tienda'>Tienda...
          <Link href='/tienda/computadores'>Computadores</Link>
          </Link> <br />
          <Link href='/posts'>Posts</Link> <br />
        </nav>
        {children}
        </body>
    </html>
  );
}
